### ISSUE TITLE
Validate ERC223 implementation and ERC20 backward compatibility

### ISSUE THREAD

**Issue by sla-shi** [MFChain/smart-contracts#104]
Validate ERC223 implementation and ERC20 backward compatibility.

Review ERC223 (https://github.com/ethereum/EIPs/issues/223) implementation: we now have `transferFrom` method which seems to be removed from the recommended ERC223 (https://github.com/Dexaran/ERC223-token-standard/tree/Recommended).
Decide if we need to update our current implementation.

**Comment by serebrov** [comment]
The ERC20's main problem is that it is possible to transfer tokens to an unaware contract address (the contract that doesn't expect to receive the tokens and doesn't know what to do with them, so the tokens will be lost and stuck at the contract address).

So the flow for contracts in ERC20 is this: user calls `token.approve(spender=contract, amount)` to allow the contract withdraw the tokens, then it calls `contract.deposit(amount)` and contract calls `token.transferFrom(user, contract, amount)` to get the tokens.
This way we are sure the contract knows what to do with tokens.
But the user is still able to call the wrong method (`transfer`) and mistakenly send the tokens to the wrong contract and loose them forever.

The ERC223 fixes that by adding the `tokenFallback` callback to make sure the contract expects the tokens, the overall flow is this: user calls `token.transfer(to=contract)`, the `transfer` method detects that `to` is a contract address and calls `contract.tokenFallback`, the contract handles the call, if everything is good, the transfer is made.
If something goes wrong, for example the contract doesn't have the `tokenFallback`, the transfer is interrupted.

The recommended ERC223 implementation (https://github.com/Dexaran/ERC223-token-standard/tree/Recommended) only has `transfer` method (no `approve` / `transferFrom`),
so it is not backwards compatible with the ERC20 standard.

There are two alternative implementations:

- By Aragon (https://github.com/aragon/ERC23), also there is a copy in Dexaran's repository (https://github.com/Dexaran/ERC223-token-standard/tree/Arago)
- The `ERC20_compatible` branch in the Dexaran's repository (https://github.com/Dexaran/ERC223-token-standard/tree/ERC20_compatible) - but it seems to be outdated comparing to the Recommended branch.

We are using Aragon's version (which he actually calls `ERC23` standard, not `ERC223`).

The Dexaran's recommened version defines these interfaces for ERC223 token and receiving contract:

```
contract ERC223Interface {
    uint public totalSupply;
    function balanceOf(address who) constant returns (uint);
    function transfer(address to, uint value);
    function transfer(address to, uint value, bytes data);
    event Transfer(address indexed from, address indexed to, uint value, bytes indexed data);
}

contract ERC223ReceivingContract { 
    /**
     * @dev Standard ERC223 function that will handle incoming token transfers.
     *
     * @param _from  Token sender address.
     * @param _value Amount of tokens.
     * @param _data  Transaction metadata.
     */
    function tokenFallback(address _from, uint _value, bytes _data);
}
```

In our current implementation of the token we have all these methods (and we use the compatible `tokenFallback` signature), so it is compatible with ERC223 (and with ERC20 too).

Since we want to be backwards compatible with ERC20, we should keep our current implementation and check the recent changes in Aragon's implementation (https://github.com/aragon/ERC23) and port them if needed.

**Comment by serebrov** [comment]
Question by @Norfolks - at the moment we are calling `tokenFallback` in the `transferFrom` method. It means that it will not be compatible with existing ERC20 contracts - they can use `approve` / `transferFrom` flow, but they can have no `tokenFallback`.

This way we may want to change `transferFrom` implementation (don't use `tokenFallback`).
